apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fintech-ingress
  namespace: fintech-prod
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - auth.13.127.208.24.nip.io
    - bank.13.127.208.24.nip.io
    secretName: fintech-tls-secret
  rules:
  - host: auth.13.127.208.24.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: keycloak
            port:
              number: 8080

  - host: bank.13.127.208.24.nip.io
    http:
      paths:
      - path: /api/v1/user(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: user-service
            port:
              number: 80

      - path: /api/v1/transaction(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: fund-transfer
            port:
              number: 80

      - path: /api/v1/account(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: internet-banking-core-service
            port:
              number: 80
